[env:esp32-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-p4
framework = arduino

; 开启 USB 串口，并包含所有可能的头文件路径
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=4
    -D LV_CONF_INCLUDE_SIMPLE=1
    -I .
    -I src
    -I src/include
    -I src/lcd
    -I src/touch

; 使用双星号 **，强制递归编译 src 下所有层级的 .c 和 .cpp 文件！
build_src_filter = +<**/*.c> +<**/*.cpp>

monitor_speed = 115200

lib_deps = 
    lvgl/lvgl@~9.2.2
    miguelbalboa/MFRC522@^1.4.11 
    bblanchon/ArduinoJson@^7.0.4

board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB